version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=turntable.proxy.rlwy.net
      - DB_USER=root
      - DB_PASSWORD=zAbgeCNfUOmgRMUjooltDVFfoifYOBXQ
      - DB_PORT=15309
      - DB_NAME=railway
      - PORT=5000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zAbgeCNfUOmgRMUjooltDVFfoifYOBXQ
      - MYSQL_DATABASE=railway
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: 